// CUDALM — .cudalm v2 container cross-language format test (CPU).
//
// Fixtures are generated by tests/fixtures/gen_v2_format.py (stdlib Python,
// the same container layout as tools/common/cudalm_v2.py): one fully valid
// synthetic file + 13 corruption cases. This test proves the C++ reader
// (weight_loader_v2.cpp) accepts exactly the valid file, rejects every
// corruption, and that the config blob / tensor table / payloads written by
// Python are bit-level understandable by C++ (per-tensor byte-size +
// wrapped byte-sum from sums.txt).

#include "../../tests/common/check.h"

#include "cudalm/weight_loader_v2.h"

#include <cstdint>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace cudalm;

namespace {

std::vector<std::uint8_t> read_file(const std::string& path, bool* ok) {
  std::vector<std::uint8_t> out;
  std::ifstream f(path, std::ios::binary);
  if (!f) { *ok = false; return out; }
  f.seekg(0, std::ios::end);
  const std::streamoff n = f.tellg();
  f.seekg(0, std::ios::beg);
  out.resize(static_cast<std::size_t>(n));
  if (n > 0) f.read(reinterpret_cast<char*>(out.data()), n);
  *ok = static_cast<bool>(f);
  return out;
}

struct SumRec {
  std::uint64_t byte_size = 0;
  std::uint64_t sum = 0;
};

int test_valid_file(const std::string& dir) {
  bool ok = true;
  const std::vector<std::uint8_t> sums_raw = read_file(dir + "/sums.txt", &ok);
  CHECK(ok);

  std::map<std::string, SumRec> sums;
  {
    std::istringstream ss(std::string(sums_raw.begin(), sums_raw.end()));
    std::string line;
    while (std::getline(ss, line)) {
      if (line.empty()) continue;
      const std::size_t t1 = line.find('\t');
      const std::size_t t2 = line.find('\t', t1 + 1);
      CHECK(t1 != std::string::npos && t2 != std::string::npos);
      const std::string name = line.substr(0, t1);
      SumRec r;
      r.byte_size = std::stoull(line.substr(t1 + 1, t2 - t1 - 1));
      r.sum = std::stoull(line.substr(t2 + 1));
      sums[name] = r;
    }
  }
  CHECK_EQ(sums.size(), 41u);  // 21 (FA layer 3) + 19 (DN layer 0) + norm

  WeightFileV2 file;
  Status s = WeightFileV2::load(dir + "/valid.cudalm", &file);
  CHECK(s.ok);
  if (!s.ok) { std::fprintf(stderr, "load error: %s\n", s.message.c_str()); return 1; }

  // Metadata / arch (Python-written, C++-read).
  CHECK_EQ(file.arch(), "synthetic-qwen3.5-format-test");
  CHECK(file.meta("model_repo") != nullptr);
  CHECK_EQ(*file.meta("model_repo"), "cudalm/synthetic");

  // Config blob: every field, Python-written, C++-parsed.
  const Qwen35Config& c = file.config();
  CHECK(c.valid());
  CHECK_EQ(c.hidden_size, 256);
  CHECK_EQ(c.num_hidden_layers, 4);
  CHECK_EQ(c.intermediate_size, 768);
  CHECK_EQ(c.vocab_size, 1000);
  CHECK_EQ(c.n_heads, 2);
  CHECK_EQ(c.n_kv_heads, 1);
  CHECK_EQ(c.head_dim, 64);
  CHECK_EQ(c.lin_num_k_heads, 2);
  CHECK_EQ(c.lin_num_v_heads, 2);
  CHECK_EQ(c.lin_key_head_dim, 32);
  CHECK_EQ(c.lin_value_head_dim, 64);
  CHECK_EQ(c.lin_conv_kernel_dim, 4);
  CHECK_EQ(c.full_attention_interval, 4);
  CHECK_EQ(c.group_size, 128);
  CHECK_EQ(c.max_seq_len, 512);
  CHECK(c.eps == 1e-6f);
  CHECK(c.rope_theta == 1e7f);
  CHECK(c.partial_rotary_factor == 0.25f);
  CHECK_EQ(c.mrope_section[0], 3);
  CHECK_EQ(c.mrope_section[1], 3);
  CHECK_EQ(c.mrope_section[2], 2);
  CHECK(c.is_full_attention(3) && !c.is_full_attention(0) &&
        !c.is_full_attention(1) && !c.is_full_attention(2));

  // Tensor table: count, per-tensor byte size + wrapped byte sum (payloads
  // bit-exact across the language boundary).
  CHECK_EQ(file.num_tensors(), sums.size());
  for (const auto& t : file.tensors()) {
    const auto it = sums.find(t.name);
    CHECK(it != sums.end());
    if (it == sums.end()) continue;
    CHECK_EQ(t.byte_size, it->second.byte_size);
    std::uint64_t sum = 0;
    for (std::size_t i = 0; i < t.byte_size; ++i) sum += t.host_bytes[i];
    CHECK_EQ(sum, it->second.sum);
  }

  // Layer-set validation: layers 0 (DN) and 3 (FA) present; 1, 2 absent.
  CHECK(file.validate_layer(0).ok);
  CHECK(file.validate_layer(3).ok);
  CHECK(!file.validate_layer(1).ok);
  CHECK(!file.validate_layer(2).ok);
  CHECK(!file.validate_layer(4).ok);
  CHECK(file.validate_model_norm().ok);

  const Qwen35TensorInfo* norm = file.find("norm.weight");
  CHECK(norm != nullptr);
  if (norm != nullptr) {
    CHECK_EQ(norm->dtype, Dtype::kBf16);
    CHECK_EQ(norm->dims.size(), 1u);
    CHECK_EQ(norm->dims[0], 256);
    CHECK_EQ(norm->byte_size, 512u);
  }
  TEST_PASS("cudalm_v2_format valid file");
  return 0;
}

int test_corruptions(const std::string& dir) {
  const char* cases[] = {
      "bad_magic", "bad_version", "bad_flags", "bad_config_size",
      "section_overlap", "payload_unaligned", "payload_oob", "bad_dtype",
      "entry_pad_nonzero", "table_trailing", "dup_name",
      "bad_name_charset", "invalid_config",
  };
  for (const char* c : cases) {
    WeightFileV2 file;
    Status s = WeightFileV2::load(std::string(dir) + "/corrupt_" + c + ".cudalm", &file);
    if (s.ok) {
      std::fprintf(stderr, "corruption case %s was ACCEPTED\n", c);
      return 1;
    }
    std::fprintf(stderr, "  rejected %s: %s\n", c, s.message.c_str());
  }
  TEST_PASS("cudalm_v2_format 13 corruption cases rejected");
  return 0;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2) {
    std::fprintf(stderr, "usage: %s <fixture_dir>\n", argv[0]);
    return 2;
  }
  const std::string dir = argv[1];
  int rc = 0;
  rc |= test_valid_file(dir);
  rc |= test_corruptions(dir);
  if (rc != 0) std::fprintf(stderr, "test_cudalm_v2_format FAILED\n");
  return rc;
}
